"""initial schema

Revision ID: d51bead6814e
Revises: 
Create Date: 2026-08-20 21:23:00.492017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51bead6814e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_health_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=96), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity', native_enum=False, length=12), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_health_checks'))
    )
    with op.batch_alter_table('data_health_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_health_checks_check_name'), ['check_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_health_checks_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index('ix_data_health_checks_open', ['check_name', 'resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_health_checks_severity'), ['severity'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('TEAM', 'PLAYER', 'EVENT', 'VENUE', name='entitytype', native_enum=False, length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_type', 'alias', 'source', name=op.f('uq_entity_aliases_entity_type_alias_source'))
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_entity_id'), ['entity_id'], unique=False)

    op.create_table('external_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('TEAM', 'PLAYER', 'EVENT', 'VENUE', name='entitytype', native_enum=False, length=16), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_ids')),
    sa.UniqueConstraint('entity_type', 'provider', 'provider_id', name=op.f('uq_external_ids_entity_type_provider_provider_id'))
    )
    with op.batch_alter_table('external_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_ids_entity_id'), ['entity_id'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=96), nullable=False),
    sa.Column('sport_key', sa.String(length=32), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='jobstatus', native_enum=False, length=12), nullable=False),
    sa.Column('counters', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_sport_key'), ['sport_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_status'), ['status'], unique=False)

    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=160), nullable=False),
    sa.Column('sport_key', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_payloads'))
    )
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_payloads_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_payloads_sport_key'), ['sport_key'], unique=False)

    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sports')),
    sa.UniqueConstraint('key', name=op.f('uq_sports_key'))
    )
    op.create_table('sportsbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('book_type', sa.Enum('SHARP', 'RECREATIONAL', 'EXCHANGE', name='booktype', native_enum=False, length=16), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('is_executable', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sportsbooks')),
    sa.UniqueConstraint('key', name=op.f('uq_sportsbooks_key'))
    )
    op.create_table('unmatched_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('TEAM', 'PLAYER', 'EVENT', 'VENUE', name='entitytype', native_enum=False, length=16), nullable=False),
    sa.Column('raw_value', sa.String(length=256), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('resolved_to_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmatched_entities'))
    )
    with op.batch_alter_table('unmatched_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unmatched_entities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_unmatched_entities_raw_value'), ['raw_value'], unique=False)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('roof', sa.String(length=32), nullable=True),
    sa.Column('park_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('feature_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_feature_sets_sport_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_sets')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_feature_sets_name_version'))
    )
    with op.batch_alter_table('feature_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_sets_sport_id'), ['sport_id'], unique=False)

    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('season_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_leagues_sport_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leagues')),
    sa.UniqueConstraint('sport_id', 'key', name=op.f('uq_leagues_sport_id_key'))
    )
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leagues_sport_id'), ['sport_id'], unique=False)

    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.Enum('MONEYLINE', 'SPREAD', 'TOTAL', 'TEAM_TOTAL', 'PLAYER_PROP', name='markettype', native_enum=False, length=16), nullable=False),
    sa.Column('period', sa.Enum('GAME', 'FIRST_HALF', 'SECOND_HALF', 'FIRST_QUARTER', 'SECOND_QUARTER', 'THIRD_QUARTER', 'FOURTH_QUARTER', 'INNINGS_1_5', name='period', native_enum=False, length=16), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_markets_sport_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('sport_id', 'market_type', 'period', name=op.f('uq_markets_sport_id_market_type_period'))
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_sport_id'), ['sport_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.String(length=24), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('feature_set_id', sa.Integer(), nullable=True),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('val_start', sa.Date(), nullable=True),
    sa.Column('val_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('artifact_hash', sa.String(length=96), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name=op.f('fk_model_versions_feature_set_id')),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_model_versions_sport_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_model_versions_name_version'))
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_sport_id'), ['sport_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('abbreviation', sa.String(length=8), nullable=True),
    sa.Column('conference', sa.String(length=32), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_teams_league_id')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_teams_venue_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('league_id', 'key', name=op.f('uq_teams_league_id_key'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_league_id'), ['league_id'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('feature_set_id', sa.Integer(), nullable=True),
    sa.Column('filter_version', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('sanity_checks', sa.JSON(), nullable=True),
    sa.Column('passed_sanity', sa.Boolean(), nullable=False),
    sa.Column('test_set_uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name=op.f('fk_backtests_feature_set_id')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_backtests_model_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_passed_sanity'), ['passed_sanity'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'FINAL', 'POSTPONED', 'CANCELLED', name='eventstatus', native_enum=False, length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_events_away_team_id')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_events_home_team_id')),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_events_league_id')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_events_venue_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('league_id', 'event_date', 'home_team_id', 'away_team_id', 'game_number', name=op.f('uq_events_league_id_event_date_home_team_id_away_team_id_game_number'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=16), nullable=True),
    sa.Column('bats', sa.String(length=4), nullable=True),
    sa.Column('throws', sa.String(length=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], name=op.f('fk_players_league_id')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('event_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('feature_set_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('missing_features', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_features_event_id')),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name=op.f('fk_event_features_feature_set_id')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_event_features_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_features')),
    sa.UniqueConstraint('event_id', 'team_id', 'feature_set_id', 'as_of', name=op.f('uq_event_features_event_id_team_id_feature_set_id_as_of'))
    )
    with op.batch_alter_table('event_features', schema=None) as batch_op:
        batch_op.create_index('ix_event_features_event_as_of', ['event_id', 'as_of'], unique=False)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STARTING_PITCHER', 'RELIEF_PITCHER', 'GOALIE', 'QUARTERBACK', 'LINEUP', 'STARTER', name='participantrole', native_enum=False, length=24), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PROJECTED', 'CONFIRMED', 'SCRATCHED', name='participantstatus', native_enum=False, length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_participants_event_id')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_event_participants_player_id')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_event_participants_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_participants'))
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_team_id'), ['team_id'], unique=False)

    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_injuries_player_id')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_injuries_team_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injuries'))
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injuries_team_id'), ['team_id'], unique=False)

    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('EVENT', 'TEAM', 'PLAYER', name='subjecttype', native_enum=False, length=12), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('HOME', 'AWAY', 'OVER', 'UNDER', 'YES', 'NO', 'DRAW', name='side', native_enum=False, length=8), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_selections_event_id')),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_selections_market_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selections')),
    sa.UniqueConstraint('event_id', 'market_id', 'subject_type', 'subject_id', 'side', 'line', name=op.f('uq_selections_event_id_market_id_subject_type_subject_id_side_line'))
    )
    with op.batch_alter_table('selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selections_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selections_market_id'), ['market_id'], unique=False)

    op.create_table('backtest_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('fair_prob', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('price_decimal', sa.Float(), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Enum('WIN', 'LOSS', 'PUSH', 'VOID', name='betoutcome', native_enum=False, length=8), nullable=True),
    sa.Column('profit_units', sa.Float(), nullable=True),
    sa.Column('clv_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_bets_backtest_id')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_backtest_bets_event_id')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_backtest_bets_selection_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_bets'))
    )
    with op.batch_alter_table('backtest_bets', schema=None) as batch_op:
        batch_op.create_index('ix_backtest_bets_backtest_as_of', ['backtest_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_bets_backtest_id'), ['backtest_id'], unique=False)

    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('price_american', sa.Float(), nullable=False),
    sa.Column('price_decimal', sa.Float(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_odds_snapshots_selection_id')),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], name=op.f('fk_odds_snapshots_sportsbook_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots'))
    )
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_odds_snapshots_captured_at', ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_odds_snapshots_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_odds_snapshots_sel_book_time', ['selection_id', 'sportsbook_id', 'captured_at'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('event_features_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('prob_lower', sa.Float(), nullable=True),
    sa.Column('prob_upper', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_features_id'], ['event_features.id'], name=op.f('fk_predictions_event_features_id')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_predictions_event_id')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_predictions_selection_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('selection_id', 'model_version_id', 'as_of', name=op.f('uq_predictions_selection_id_model_version_id_as_of'))
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index('ix_predictions_selection_as_of', ['selection_id', 'as_of'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('reference_odds_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('reference_book_count', sa.Integer(), nullable=False),
    sa.Column('market_implied_prob', sa.Float(), nullable=False),
    sa.Column('market_fair_prob', sa.Float(), nullable=False),
    sa.Column('novig_method', sa.String(length=16), nullable=False),
    sa.Column('reference_dispersion', sa.Float(), nullable=True),
    sa.Column('best_odds_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('best_sportsbook_id', sa.Integer(), nullable=True),
    sa.Column('best_price_american', sa.Float(), nullable=True),
    sa.Column('best_price_decimal', sa.Float(), nullable=True),
    sa.Column('model_prob', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('structural_edge', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('expected_roi', sa.Float(), nullable=False),
    sa.Column('line_age_seconds', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('model_agreement', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closing_odds_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('closing_fair_prob', sa.Float(), nullable=True),
    sa.Column('clv_probability', sa.Float(), nullable=True),
    sa.Column('model_beat_close', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['best_odds_snapshot_id'], ['odds_snapshots.id'], name=op.f('fk_candidates_best_odds_snapshot_id')),
    sa.ForeignKeyConstraint(['best_sportsbook_id'], ['sportsbooks.id'], name=op.f('fk_candidates_best_sportsbook_id')),
    sa.ForeignKeyConstraint(['closing_odds_snapshot_id'], ['odds_snapshots.id'], name=op.f('fk_candidates_closing_odds_snapshot_id')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_candidates_event_id')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_candidates_prediction_id')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_candidates_selection_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_as_of', ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_edge'), ['edge'], unique=False)
        batch_op.create_index('ix_candidates_event_as_of', ['event_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_selection_id'), ['selection_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_version', sa.Integer(), nullable=False),
    sa.Column('recommended_stake_units', sa.Float(), nullable=False),
    sa.Column('sizing_method', sa.String(length=24), nullable=False),
    sa.Column('kelly_fraction', sa.Float(), nullable=True),
    sa.Column('was_stake_capped', sa.Boolean(), nullable=False),
    sa.Column('filter_version', sa.String(length=32), nullable=False),
    sa.Column('passed_filters', sa.JSON(), nullable=True),
    sa.Column('failed_filters', sa.JSON(), nullable=True),
    sa.Column('correlation_group', sa.String(length=96), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'EXPIRED', name='recommendationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_recommendations_candidate_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_confidence_score'), ['confidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_correlation_group'), ['correlation_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook_id', sa.Integer(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('stake_units', sa.Float(), nullable=False),
    sa.Column('price_american_taken', sa.Float(), nullable=False),
    sa.Column('price_decimal_taken', sa.Float(), nullable=False),
    sa.Column('line_taken', sa.Float(), nullable=True),
    sa.Column('fair_prob_at_bet', sa.Float(), nullable=False),
    sa.Column('model_prob_at_bet', sa.Float(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('filter_version', sa.String(length=32), nullable=True),
    sa.Column('confidence_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_bets_model_version_id')),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_bets_recommendation_id')),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], name=op.f('fk_bets_selection_id')),
    sa.ForeignKeyConstraint(['sportsbook_id'], ['sportsbooks.id'], name=op.f('fk_bets_sportsbook_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bets'))
    )
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bets_is_paper'), ['is_paper'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_recommendation_id'), ['recommendation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_selection_id'), ['selection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bets_sportsbook_id'), ['sportsbook_id'], unique=False)

    op.create_table('recommendation_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('factor_key', sa.String(length=96), nullable=False),
    sa.Column('factor_label', sa.String(length=160), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('MODEL_COEFFICIENT', 'SHAP', 'MARKET', name='reasonsource', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_reasons_recommendation_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_reasons'))
    )
    with op.batch_alter_table('recommendation_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_reasons_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('bet_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('WIN', 'LOSS', 'PUSH', 'VOID', name='betoutcome', native_enum=False, length=8), nullable=False),
    sa.Column('profit_units', sa.Float(), nullable=False),
    sa.Column('closing_odds_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('closing_price_decimal', sa.Float(), nullable=True),
    sa.Column('closing_fair_prob', sa.Float(), nullable=True),
    sa.Column('clv_price', sa.Float(), nullable=True),
    sa.Column('clv_probability', sa.Float(), nullable=True),
    sa.Column('beat_closing_line', sa.Boolean(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settlement_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], name=op.f('fk_bet_results_bet_id')),
    sa.ForeignKeyConstraint(['closing_odds_snapshot_id'], ['odds_snapshots.id'], name=op.f('fk_bet_results_closing_odds_snapshot_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bet_results')),
    sa.UniqueConstraint('bet_id', name=op.f('uq_bet_results_bet_id'))
    )
    with op.batch_alter_table('bet_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bet_results_settled_at'), ['settled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bet_results_settled_at'))

    op.drop_table('bet_results')
    with op.batch_alter_table('recommendation_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_reasons_recommendation_id'))

    op.drop_table('recommendation_reasons')
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bets_sportsbook_id'))
        batch_op.drop_index(batch_op.f('ix_bets_selection_id'))
        batch_op.drop_index(batch_op.f('ix_bets_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_bets_placed_at'))
        batch_op.drop_index(batch_op.f('ix_bets_is_paper'))

    op.drop_table('bets')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_correlation_group'))
        batch_op.drop_index(batch_op.f('ix_recommendations_confidence_score'))
        batch_op.drop_index(batch_op.f('ix_recommendations_candidate_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_selection_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_event_id'))
        batch_op.drop_index('ix_candidates_event_as_of')
        batch_op.drop_index(batch_op.f('ix_candidates_edge'))
        batch_op.drop_index('ix_candidates_as_of')

    op.drop_table('candidates')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index('ix_predictions_selection_as_of')
        batch_op.drop_index(batch_op.f('ix_predictions_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_event_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('odds_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_odds_snapshots_sel_book_time')
        batch_op.drop_index(batch_op.f('ix_odds_snapshots_run_id'))
        batch_op.drop_index('ix_odds_snapshots_captured_at')

    op.drop_table('odds_snapshots')
    with op.batch_alter_table('backtest_bets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_bets_backtest_id'))
        batch_op.drop_index('ix_backtest_bets_backtest_as_of')

    op.drop_table('backtest_bets')
    with op.batch_alter_table('selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selections_market_id'))
        batch_op.drop_index(batch_op.f('ix_selections_event_id'))

    op.drop_table('selections')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_team_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_player_id'))
        batch_op.drop_index(batch_op.f('ix_injuries_observed_at'))

    op.drop_table('injuries')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_team_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_player_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_observed_at'))
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))

    op.drop_table('event_participants')
    with op.batch_alter_table('event_features', schema=None) as batch_op:
        batch_op.drop_index('ix_event_features_event_as_of')

    op.drop_table('event_features')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_league_id'))
        batch_op.drop_index(batch_op.f('ix_players_full_name'))

    op.drop_table('players')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_events_season'))
        batch_op.drop_index(batch_op.f('ix_events_league_id'))
        batch_op.drop_index(batch_op.f('ix_events_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_events_away_team_id'))

    op.drop_table('events')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_passed_sanity'))
        batch_op.drop_index(batch_op.f('ix_backtests_model_version_id'))

    op.drop_table('backtests')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_league_id'))

    op.drop_table('teams')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_sport_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_is_active'))

    op.drop_table('model_versions')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_sport_id'))

    op.drop_table('markets')
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leagues_sport_id'))

    op.drop_table('leagues')
    with op.batch_alter_table('feature_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_sets_sport_id'))

    op.drop_table('feature_sets')
    op.drop_table('venues')
    with op.batch_alter_table('unmatched_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_entities_raw_value'))
        batch_op.drop_index(batch_op.f('ix_unmatched_entities_provider'))

    op.drop_table('unmatched_entities')
    op.drop_table('sportsbooks')
    op.drop_table('sports')
    with op.batch_alter_table('raw_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_payloads_sport_key'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_run_id'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_provider'))
        batch_op.drop_index(batch_op.f('ix_raw_payloads_observed_at'))

    op.drop_table('raw_payloads')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_status'))
        batch_op.drop_index(batch_op.f('ix_job_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_job_runs_sport_key'))
        batch_op.drop_index(batch_op.f('ix_job_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    with op.batch_alter_table('external_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_ids_entity_id'))

    op.drop_table('external_ids')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_alias'))

    op.drop_table('entity_aliases')
    with op.batch_alter_table('data_health_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_health_checks_severity'))
        batch_op.drop_index('ix_data_health_checks_open')
        batch_op.drop_index(batch_op.f('ix_data_health_checks_detected_at'))
        batch_op.drop_index(batch_op.f('ix_data_health_checks_check_name'))

    op.drop_table('data_health_checks')
    # ### end Alembic commands ###
